


/* Generated by glib-mkenums. Do not edit */

#ifndef __MEGA_ENUM_TYPES_H__
#define __MEGA_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
GType mega_hex_format_get_type (void) G_GNUC_CONST;
#define MEGA_TYPE_HEX_FORMAT (mega_hex_format_get_type ())
G_END_DECLS

#endif /* __MEGA_ENUM_TYPES_H__ */



